### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'TopCoder Statistics - Problem Archive.html'

### ISSUE THREAD

**Issue by ghost** [biswajitsc/TopcoderToPdf#1]
I am getting this error when I am executing the python files.should I have to create TopCoder Statistics - Problem Archive.html file?

**Comment by biswajitsc** [comment]
Is the issue resolved ? If not, I would look into it.

**Comment by gaddevarunteja** [comment]
Does it work for windows?

**Comment by ghost** [comment]
Should I change code if I am using windows ?

**Comment by ghost** [comment]
The input error is resolved but I am unable open the files using 
open('./htmls/') 
what should it be for windows?

**Comment by biswajitsc** [comment]
The path separator in windows is '\' instead of '/'. So you would have to use open('.\htmls\') perhaps. Better option is to use os.pathsep to make it platform free.
Can you tell me the file where you got this error: IOError: [Errno 2] No such file or directory: 'TopCoder Statistics - Problem Archive.html' .
Thanks.

**Comment by ghost** [comment]
topcoderGenPdf

**Comment by ghost** [comment]
IOError: No wkhtmltopdf executable found: ""
If this file exists please check that this process can read it
I have installed wkhtmltopdf but still it is showing the above error.

**Comment by ghost** [comment]
Traceback (most recent call last):
  File "C:\Users\Varun\Downloads\TopcoderToPdf-master\topcoderGenPdf.py", line 55, in <module>
    pdfkit.from_file(open('.\proc_htmls\{0}'.format(filename)), '.\PDFs\{0}.pdf'.format(filename), options = options)
  File "C:\Python27\lib\site-packages\pdfkit\api.py", line 44, in from_file
    configuration=None)
  File "C:\Python27\lib\site-packages\pdfkit\pdfkit.py", line 38, in **init**
    self.configuration = (Configuration() if configuration is None
  File "C:\Python27\lib\site-packages\pdfkit\configuration.py", line 27, in **init**
    'https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf' % self.wkhtmltopdf)
IOError: No wkhtmltopdf executable found: ""
If this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf

**Comment by biswajitsc** [comment]
Have you tried using wkhtmltopdf to test whether it works? If it works can you tell me what command did you use to run it on windows?

**Comment by ghost** [comment]
Yes it works when I enter wkhtmltopdf in terminal.

**Comment by ghost** [comment]
After setting path I get the below error

Traceback (most recent call last):
  File "C:\Users\Varun\Downloads\TopcoderToPdf-master\topcoderGenPdf.py", line 55, in <module>
    pdfkit.from_file(open('.\proc_htmls\{0}'.format(filename)), '.\PDFs\{0}.pdf'.format(filename), options = options)
  File "C:\Python27\lib\site-packages\pdfkit\api.py", line 46, in from_file
    return r.to_pdf(output_path)
  File "C:\Python27\lib\site-packages\pdfkit\pdfkit.py", line 116, in to_pdf
    raise IOError('wkhtmltopdf reported an error:\n' + stderr.decode('utf-8'))
IOError: wkhtmltopdf reported an error:
Loading pages (1/6)

[>                                                           ] 0%
[======>                                                     ] 10%
[=========>                                                  ] 16%
Warning: Failed to load http://community.topcoder.com/js/reskin/newTCScript.js (ignore)

Warning: Failed to load http://community.topcoder.com/css/coders.css (ignore)

Warning: Failed to load http://community.topcoder.com/css/jobsRemix.css (ignore)

Warning: Failed to load http://community.topcoder.com/css/reskin/myHome.css (ignore)

Warning: Failed to load http://community.topcoder.com/css/reskin/newStyles.css (ignore)

Warning: Failed to load http://community.topcoder.com/i/clear.gif (ignore)

Warning: Failed to load http://community.topcoder.com/i/steelblue_top_left1.gif (ignore)

Warning: Failed to load http://community.topcoder.com/i/steel_gray_bg.gif (ignore)

Warning: Failed to load http://community.topcoder.com/i/steel_blue_bg.gif (ignore)

Warning: Failed to load http://www.google-analytics.com/ga.js (ignore)

[============================================================] 100%
Counting pages (2/6)                                               

[============================================================] Object 1 of 1
Resolving links (4/6)                                                       

[============================================================] Object 1 of 1
Loading headers and footers (5/6)                                           

Printing pages (6/6)

[>                                                           ] Preparing
[===================>                                        ] Page 1 of 3
[=======================================>                    ] Page 2 of 3
[============================================================] Page 3 of 3
Done                                                                      

Exit with code 1 due to network error: TimeoutError

**Comment by biswajitsc** [comment]
I think the issue that you are facing is this: http://stackoverflow.com/questions/27673870/cant-create-pdf-using-python-pdfkit-error-no-wkhtmltopdf-executable-found
See if the above link resolves the issue.

**Comment by ghost** [comment]
No it didnot resolve the issue

**Comment by ghost** [comment]
After setting path I get the below error

Traceback (most recent call last):
File "C:\Users\Varun\Downloads\TopcoderToPdf-master\topcoderGenPdf.py", line 55, in 
pdfkit.from_file(open('.\proc_htmls{0}'.format(filename)), '.\PDFs{0}.pdf'.format(filename), options = options)
File "C:\Python27\lib\site-packages\pdfkit\api.py", line 46, in from_file
return r.to_pdf(output_path)
File "C:\Python27\lib\site-packages\pdfkit\pdfkit.py", line 116, in to_pdf
raise IOError('wkhtmltopdf reported an error:\n' + stderr.decode('utf-8'))
IOError: wkhtmltopdf reported an error:
Loading pages (1/6)

[> ] 0%
[======> ] 10%
[=========> ] 16%
Warning: Failed to load http://community.topcoder.com/js/reskin/newTCScript.js (ignore)

Warning: Failed to load http://community.topcoder.com/css/coders.css (ignore)

Warning: Failed to load http://community.topcoder.com/css/jobsRemix.css (ignore)

Warning: Failed to load http://community.topcoder.com/css/reskin/myHome.css (ignore)

Warning: Failed to load http://community.topcoder.com/css/reskin/newStyles.css (ignore)

Warning: Failed to load http://community.topcoder.com/i/clear.gif (ignore)

Warning: Failed to load http://community.topcoder.com/i/steelblue_top_left1.gif (ignore)

Warning: Failed to load http://community.topcoder.com/i/steel_gray_bg.gif (ignore)

Warning: Failed to load http://community.topcoder.com/i/steel_blue_bg.gif (ignore)

Warning: Failed to load http://www.google-analytics.com/ga.js (ignore)

[============================================================] 100%
Counting pages (2/6)

[============================================================] Object 1 of 1
Resolving links (4/6)

[============================================================] Object 1 of 1
Loading headers and footers (5/6)

Printing pages (6/6)

[> ] Preparing
[===================> ] Page 1 of 3
[=======================================> ] Page 2 of 3
[============================================================] Page 3 of 3
Done

Exit with code 1 due to network error: TimeoutError

**Comment by biswajitsc** [comment]
Have you tried testing wkhtmltopdf manually. Try to print a webpage using wkhtmltopdf from command line. For e.g. `wkhtmltopdf http://google.com google.pdf`

**Comment by ghost** [comment]
It is displaying this when I give wkhtmltopdf http://google.com google.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

**Comment by biswajitsc** [comment]
There was a proxy setting in topcoderGenPdf.py file. Kindly comment that line. Now it should work.

**Comment by biswajitsc** [comment]
The proxy setting was there in line 51 of topcoderGenPdf.py. Commenting that line should solve it.

**Comment by ghost** [comment]
What about filemerger.py? I get following errors

Traceback (most recent call last):
  File "C:\Users\Varun\Downloads\TopcoderToPdf-master\filemerger.py", line 90, in <module>
    main()
  File "C:\Users\Varun\Downloads\TopcoderToPdf-master\filemerger.py", line 68, in main
    merger.append(inp)
  File "C:\Python27\lib\site-packages\PyPDF2\merger.py", line 203, in append
    self.merge(len(self.pages), fileobj, bookmark, pages, import_bookmarks)
  File "C:\Python27\lib\site-packages\PyPDF2\merger.py", line 151, in merge
    outline = pdfr.getOutlines()
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 1333, in getOutlines
    outline = self._buildOutline(node)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 1420, in _buildOutline
    raise utils.PdfReadError("Unexpected destination %r" % dest)
PdfReadError: Unexpected destination '/__WKANCHOR_2'

**Comment by biswajitsc** [comment]
This error occurs because of a bug in PyPDF2. So uninstall your current version of PyPDF2 and install the version that I have provided in this repository.

**Comment by ghost** [comment]
I installed PyPDF2 in hannal's repository still it is showing the error

Traceback (most recent call last):
  File "C:\Users\Varun\Downloads\TopcoderToPdf-master\filemerger.py", line 90, in <module>
    main()
  File "C:\Users\Varun\Downloads\TopcoderToPdf-master\filemerger.py", line 68, in main
    merger.append(inp)
  File "C:\Python27\lib\site-packages\PyPDF2\merger.py", line 198, in append
    self.merge(len(self.pages), fileobj, bookmark, pages, import_bookmarks)
  File "C:\Python27\lib\site-packages\PyPDF2\merger.py", line 146, in merge
    outline = pdfr.getOutlines()
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 1180, in getOutlines
    outline = self._buildOutline(node)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 1224, in _buildOutline
    raise utils.PdfReadError("Unexpected destination %r" % dest)
PdfReadError: Unexpected destination '/__WKANCHOR_2'

**Comment by biswajitsc** [comment]
Not the one in hannal's repository. When you clone this repository, the PyPDF2 folder in my repository will also get cloned. Go to its folder and you'll find setup.py. Install this particular PyPDF2.

**Comment by ghost** [comment]
Your PyPDF2 Folder is empty.

**Comment by biswajitsc** [comment]
Use the following command to fetch all submodules present in the project:

```
git submodule update --init --recursive
```

This should fetch the PyPDF2 repo.

**Comment by ghost** [comment]
Where should I execute the above command?
In your repository the submodules of PyPDF2 are those in hannal's repository

**Comment by biswajitsc** [comment]
Execute it inside the repository folder.
Yes they are from hannal's repository but from a previous version, not the latest.

**Comment by ghost** [comment]
It says not a git repository 

fatal: Not a git repository (or any of the parent directories): .git

**Comment by biswajitsc** [comment]
That is perhaps because you didn't use git to clone the repository, but downloaded it as zip from github. You should clone the repository, and then you would be able to execute git commands.
