### ISSUE TITLE
Failed to convert to pdfs.

### ISSUE THREAD

**Issue by freegyp** [biswajitsc/TopcoderToPdf#3]
When I run topcoderGenPdf.py on macOS, it raised some errors.

Traceback (most recent call last):
  File "topcoderGenPdf.py", line 55, in <module>
    pdfkit.from_file(open('./proc_htmls/{0}'.format(filename)), './PDFs/{0}.pdf'.format(filename), options = options)
  File "/Users/admin/anaconda/lib/python2.7/site-packages/pdfkit/api.py", line 49, in from_file
    return r.to_pdf(output_path)
  File "/Users/admin/anaconda/lib/python2.7/site-packages/pdfkit/pdfkit.py", line 156, in to_pdf
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
IOError: wkhtmltopdf reported an error:
Loading pages (1/6)
Warning: Failed to load file://community.topcoder.com/js/reskin/newTCScript.js (ignore)
Warning: Failed to load file://community.topcoder.com/css/coders.css (ignore)
Warning: Failed to load file://community.topcoder.com/css/jobsRemix.css (ignore)
Warning: Failed to load file://community.topcoder.com/css/reskin/myHome.css (ignore)
Warning: Failed to load file://community.topcoder.com/css/reskin/newStyles.css (ignore)
Warning: Failed to load file://community.topcoder.com/i/clear.gif (ignore)
Warning: Failed to load file://community.topcoder.com/i/steelblue_top_left1.gif (ignore)
Warning: Failed to load file://community.topcoder.com/i/steel_gray_bg.gif (ignore)
Warning: Failed to load file://community.topcoder.com/i/steel_blue_bg.gif (ignore)
Warning: Failed to load file://i.kissmetrics.com/i.js (ignore)    
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                      
Exit with code 1 due to network error: ProtocolInvalidOperationError

**Comment by biswajitsc** [comment]
Not sure why this happens. Perhaps because of deprecated libraries. Unfortunately I am no longer updating the project to support the latest libraries. The code is really simple, I would advise you to try to fix it yourself.
